repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        pass_filenames: false
        always_run: true
      - id: end-of-file-fixer
        pass_filenames: false
        always_run: true
      - id: check-yaml
        pass_filenames: false
        always_run: true
      - id: check-json
        pass_filenames: false
        always_run: true
      - id: check-toml
        pass_filenames: false
        always_run: true
      - id: check-merge-conflict
        pass_filenames: false
        always_run: true
      - id: check-added-large-files
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: cargo-fmt-check
        name: Cargo Format Check
        entry: cargo fmt -- --check
        language: rust
        types: [rust]
        pass_filenames: false
        always_run: true
      - id: cargo-clippy
        name: Cargo Clippy
        entry: cargo clippy -- -D warnings
        language: rust
        types: [rust]
        pass_filenames: false
        always_run: true
      - id: cargo-check
        name: Cargo Check
        entry: cargo check
        language: rust
        types: [rust]
        pass_filenames: false
        always_run: true
