[package]
name = "bevy-mogura"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"

[profile.release]
opt-level = 3
lto = true
strip = true

[profile.dev]
opt-level = 3

[[bin]]
name = "mogura"
path = "src/main.rs"
