[workspace]
resolver = "2"
members = [
    "mogura-io",
    "bevy-mogura",
]

default-members = [
    "mogura-io",
    "bevy-mogura",
]

[workspace.package]
name = "mogura"
version = "0.1.0"
edition = "2021"
authors = ["th"]
description = "A molecular visualizer in Rust"

[workspace.dependencies]
bevy = "0.14.2"
clap = { version = "3.2.22", features = ["derive"]  }
pdbtbx = "0.11.0"
bevy-mogura = { path = "./bevy-mogura/" }
mogura-io = { path = "./mogura-io/" }

[profile.release]
opt-level = 3
lto = true
strip = true

[profile.dev]
opt-level = 3
