[graph]
all-features = true

[advisories]
version = 2
ignore = []

[licenses]
version = 2
allow = [
    "0BSD",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "CC0-1.0",
    "ISC",
    "MIT",
    "MIT-0",
    "Unlicense",
    "Zlib",
    "MPL-2.0",
    "Unicode-3.0",
    "OFL-1.1",
    "LicenseRef-UFL-1.0",
]

exceptions = []

[bans]
multiple-versions = "warn"
wildcards = "warn"
# Certain crates that we don't want multiple versions of in the dependency tree
deny = []
skip = [
    # { name = "log" },
    { name = "base64" },
    { name = "bit-set" },
    { name = "bit-vec" },
    { name = "bitflags" },
    { name = "event-listener" },
    { name = "ndk-sys" },
    { name = "redox_syscall" },
    { name = "thiserror" },
    { name = "thiserror-impl" },
    { name = "windows-core" },
    { name = "windows-sys" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = ["https://github.com/qu1x/bevy_trackball.git"]
