[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
skip_core_tasks = true

[tasks.wasm]
env = { RUSTFLAGS="--cfg web_sys_unstable_apis" }
workspace = false
script = '''
typst -V
cd mogura-wasm
trunk serve --open
'''
