[env]
PORT = 8000
WASM_TMP_DIR = "../mogura-wasm"

[config]
skip_core_tasks = true

[tasks.test]
script = '''
echo $PORT
'''

[tasks.fmtlint]
script = '''
cargo fmt
cargo clippy
'''

[tasks.build]
command = "cargo"
args = ["build", "-r"]

[tasks.run]
command = "cargo"
args = ["run", "-r"]

[tasks.build-wasm]
command = "trunk"
# args = ["build", "--release"]
args = ["build"]

[tasks.run-wasm]
dependencies = ["build-wasm"]
script = '''
cd dist
python -m http.server $PORT
'''

[tasks.prepare-wasm]
script = '''
trunk build --release --public-url .
rm -f $WASM_TMP_DIR/index.html
rm -f $WASM_TMP_DIR/mogura-*.js
rm -f $WASM_TMP_DIR/mogura-*.wasm
cp -r ./dist/* $WASM_TMP_DIR
sed -i -e "s/\/.\/mogura-/.\/mogura-/g" $WASM_TMP_DIR/index.html
rm -f $WASM_TMP_DIR/index.html-e
'''

[tasks.build-docker]
script = '''
docker build -t mogura .
'''

[tasks.run-docker]
script = '''
xhost +
docker run --rm -e DISPLAY=host.docker.internal:0 -v ~/.Xauthority:/root/.Xauthority -v /tmp/.X11-unix/:/tmp/.X11-unix/ -v $PWD:/mnt -w /mnt mogura mogura
xhost -
'''

