[package]
name = "bevy-mogura"
version = "0.1.0"
edition = "2021"
description = "A plugin for molecular graphic visualization"

[dependencies]
bevy.workspace = true
bevy_trackball.workspace = true
mogura-io.workspace = true
bevy_egui.workspace = true
egui.workspace = true
# bevy_file_dialog.workspace = true
rfd.workspace = true
